syntax on

set encoding=utf-8

set backspace=indent,eol,start
set number " Show line numbers
set laststatus=2 " Always show the status line
set showtabline=2 " Always show the tab bar
set spell spelllang=en_us

set incsearch " Search as you type
set hlsearch " Highlight search hits

set ruler " Show the ruler in the footer
set cursorline " Highlight line the cursor is on

set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Show trailing spaces
set list listchars=trail:·,tab:\ \ 

" 4 space tabs by default
set softtabstop=4
set shiftwidth=4
set tabstop=4
set expandtab
set smarttab

set autoindent
set smartindent

filetype plugin on

if has("gui_running")
    set guioptions=egmrLt
    set lines=40 columns=125
endif
