execute pathogen#infect()

syntax on

set encoding=utf-8

set wildmode=longest:full " Complete to longest common string, then show menu
set wildmenu " Enable completion menu

set backspace=indent,eol,start
set number " Show line numbers
set laststatus=2 " Always show the status line
set spell spelllang=en_us

set incsearch " Search as you type
set hlsearch " Highlight search hits

set ruler " Show the ruler in the footer
set cursorline " Highlight line the cursor is on

set backupcopy=yes " Fix for Karma removing spec files on save

set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Show trailing spaces
set list listchars=trail:·,tab:\ \ 

" 2 space tabs by default
set softtabstop=2
set shiftwidth=2
set tabstop=2
set expandtab
set smarttab

set autoindent
set smartindent

filetype plugin on

let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_ruby_checkers = []
let g:syntastic_eruby_checkers = []
let g:syntastic_sass_checkers = []
let g:syntastic_scss_checkers = []
let g:syntastic_html_checkers = []
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1

if has("gui_running")
    set guioptions=egmrLt
    set lines=40 columns=125
endif

colorscheme predawn

" Set highlighting for spelling errors
highlight clear SpellBad
highlight SpellBad term=standout ctermfg=1 term=underline cterm=underline
highlight clear SpellCap
highlight SpellCap term=underline cterm=underline
highlight clear SpellRare
highlight SpellRare term=underline cterm=underline
highlight clear SpellLocal
highlight SpellLocal term=underline cterm=underline
