execute pathogen#infect()

syntax on

set encoding=utf-8

set wildmode=longest:full " Complete to longest common string, then show menu
set wildmenu " Enable completion menu

set backspace=indent,eol,start
set number " Show line numbers
set laststatus=2 " Always show the status line
set spell spelllang=en_us

set incsearch " Search as you type
set hlsearch " Highlight search hits

set ruler " Show the ruler in the footer
set cursorline " Highlight line the cursor is on

set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Show trailing spaces
set list listchars=trail:·,tab:\ \ 

" 2 space tabs by default
set softtabstop=2
set shiftwidth=2
set tabstop=2
set expandtab
set smarttab

set autoindent
set smartindent

filetype plugin on

let g:syntastic_javascript_checkers = ['jsl']

if has("gui_running")
    set guioptions=egmrLt
    set lines=40 columns=125
endif
